---
- name: install knot resolver
  ansible.builtin.package:
    name:
      - knot-resolver
      - knot-resolver-module-dnstap
      - knot-resolver-module-http
      - lua5.1-filesystem
    state: present

- name: /etc/knot-resolver directory
  ansible.builtin.file:
    path: /etc/knot-resolver
    owner: root
    group: knot-resolver
    mode: '0750'
    state: directory

- name: fix file permissions
  ansible.builtin.file:
    path: '{{ item }}'
    state: touch
    owner: root
    group: knot-resolver
    mode: '0640'
    modification_time: preserve
    access_time: preserve
  loop:
    - /etc/knot-resolver/icann-ca.pem
    - /etc/knot-resolver/root.hints

- name: populate package_facts
  ansible.builtin.package_facts:
    manager: auto

- name: check that /etc/NetworkManager/NetworkManager.conf exists
  ansible.builtin.stat:
    path: /etc/NetworkManager/NetworkManager.conf
  register: kresd_network_manager_conf

- name: make sure line 'dns=none' is set in /etc/NetworkManager/NetworkManager.conf
  community.general.ini_file:
    path: /etc/NetworkManager/NetworkManager.conf
    state: present
    no_extra_spaces: true
    section: main
    option: dns
    value: none
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: kresd_network_manager_conf.stat.exists

- name: config.yaml
  ansible.builtin.template:
    src: templates/config.yaml.j2
    dest: /etc/knot-resolver/config.yaml
    owner: root
    group: knot-resolver
    mode: '0640'
  tags:
    - kresd-conf

- name: /etc/knot-resolver/config.d directory
  ansible.builtin.file:
    path: /etc/knot-resolver/config.d
    owner: root
    group: knot-resolver
    mode: '0750'
    state: directory
  tags:
    - kresd-conf

- name: config.d files
  ansible.builtin.template:
    src: '{{ item }}'
    dest: /etc/knot-resolver/config.d/{{ item | basename | regex_replace('.j2$', '') }}
    owner: root
    group: knot-resolver
    mode: '0640'
  loop:
    - 000-defaults.lua.j2
    - 650-prometheus-endpoint.lua.j2
    - 890-policy-forward.lua.j2
    - 998-view-local.lua.j2
    - 999-view-drop.lua.j2
  tags:
    - kresd-conf

- name: create directory for systemd drop-ins
  ansible.builtin.file:
    path: /etc/systemd/system/knot-resolver.service.d
    owner: root
    group: root
    state: directory
    mode: '0755'

- name: knot-resolver.service
  ansible.builtin.copy:
    content: |
      [Unit]
      Description=Knot Resolver Manager
      Documentation=man:knot-resolver.systemd(7)
      DefaultDependencies=no
      After=systemd-sysctl.service systemd-sysusers.service systemd-tmpfiles-setup.service local-fs.target systemd-journald.service
      Before=sysinit.target network.target nss-lookup.target shutdown.target initrd-switch-root.target
      Conflicts=shutdown.target initrd-switch-root.target
      Wants=nss-lookup.target

      [Service]
      Type=notify
      TimeoutStartSec=600s
      ExecStart=/usr/bin/knot-resolver --config=/etc/knot-resolver/config.yaml
      Environment=KRES_LOGGING_TARGET=syslog
      ExecReload=/usr/bin/kresctl --config=/etc/knot-resolver/config.yaml reload
      KillSignal=SIGINT
      WorkingDirectory=/var/lib/knot-resolver
      User=knot-resolver
      Group=knot-resolver
      CapabilityBoundingSet=CAP_NET_BIND_SERVICE CAP_SETPCAP
      AmbientCapabilities=CAP_NET_BIND_SERVICE CAP_SETPCAP

      [Install]
      WantedBy=sysinit.target
    dest: /etc/systemd/system/knot-resolver.service
    owner: root
    group: root
    mode: '0644'
  notify:
    - kresd daemon-reload
    - kresd enable
    - kresd update-resolv-conf

- name: ensure that systemd-resolved is disabled
  ansible.builtin.service:
    name: systemd-resolved
    enabled: false
  when: not kresd_role_debug|bool
  ignore_errors: true

- name: configure cloud-init
  ansible.builtin.template:
    src: cloud-init.conf.j2
    dest: /etc/cloud/cloud.cfg.d/10_dns.conf
    owner: root
    group: root
    mode: '0644'
  when: "'cloud-init' in ansible_facts.packages"

- ansible.builtin.include_tasks: provider-ec2.yaml
  when: provider is defined and provider == "ec2"
  tags:
    - kresd-conf
