---

- name: include escapace.aws_environment role
  include_role:
    name: escapace.aws_environment

- name: kresd.conf.d files
  template:
    src: "{{ item }}"
    dest: /etc/knot-resolver/kresd.conf.d/{{ item | basename | regex_replace('.j2$', '') }}
    owner: root
    group: knot-resolver
    mode: 0640
  loop:
    - "815-policy-ec2.conf.j2"
  tags:
  - kresd-conf
