---
- name: include escapace.aws_environment role
  ansible.builtin.include_role:
    name: escapace.aws_environment

- name: ec2-environment.conf drop-in
  ansible.builtin.copy:
    content: |
      [Service]
      EnvironmentFile=/etc/sysconfig/ec2-environment
    dest: /etc/systemd/system/knot-resolver.service.d/ec2-environment.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - kresd daemon-reload
    - kresd enable

- name: knot-resolver config.d files
  ansible.builtin.template:
    src: knot-resolver-policy-ec2.lua.j2
    dest: /etc/knot-resolver/config.d/815-policy-ec2.lua
    owner: root
    group: knot-resolver
    mode: "0640"
  tags:
    - kresd-conf
