---
- name: configure the ec2 environment systemd drop-in
  ansible.builtin.copy:
    content: |
      [Service]
      EnvironmentFile=/etc/sysconfig/ec2-environment
    dest: /etc/systemd/system/knot-resolver.service.d/ec2-environment.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - kresd daemon-reload
    - kresd restart knot-resolver

- name: configure the knot resolver ec2 policy
  ansible.builtin.template:
    src: knot-resolver-policy-ec2.lua.j2
    dest: /etc/knot-resolver/config.d/815-policy-ec2.lua
    owner: root
    group: knot-resolver
    mode: "0640"
  notify: kresd restart knot-resolver
  tags:
    - kresd-conf
