---

- name: kresd update resolv.conf
  ansible.builtin.template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    owner: root
    group: root
    mode: 0644
  when: not kresd_role_debug|bool

- name: kresd daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true
  when: not kresd_role_debug|bool
